#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "You need to specify the full branch name on which to backport the current branch, e.g. origin/branch"
    exit 1
fi

if [[ ! $1 =~ [^/]+/([^/]+) ]]; then
    echo "The argument does not look like a branch name, e.g. origin/branch"
fi

SUFFIX=${BASH_REMATCH[1]}

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
echo $CURRENT_BRANCH

git checkout -b "$CURRENT_BRANCH-$SUFFIX" $1
git cherry-pick "$CURRENT_BRANCH"

