#!/bin/bash
USER_REMOTE=$(git config --get github.userfork)
BRANCHES=$(git for-each-ref --count=100 --sort=-committerdate refs/heads/ --format='%(refname:short)'|tr '\n' ' ')
if [ -n "$BRANCH" ]; then
  git checkout "$BRANCH"
fi
for BRANCH in $BRANCHES; do
	git push -f "$USER_REMOTE" "$BRANCH"
done

